name: spaceparking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.3
  flutter_splash_screen: ^1.0.0+6
  curved_navigation_bar: ^1.0.3
  http: ^0.13.4
  flutter_otp_text_field: ^1.1.1
  google_fonts: ^4.0.4
  flutter_vector_icons: ^2.0.0
  flutter_bloc: ^8.1.3
  camera: ^0.10.5+2
  image: ^4.0.17
  tflite_flutter: ^0.10.1
  flutter_hooks: ^0.18.6
  data_table_2: ^2.5.2
  #tflite: ^1.1.2
  foundation: ^0.0.5
  sqflite: ^2.2.8+4
  sqflite_common_ffi_web: ^0.3.5+1
  file_picker: ^5.3.2
  video_player: ^2.6.1
  permission_handler: ^10.3.0
  shared_preferences: ^2.1.2
  flutter_svg: ^2.0.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
  - assets/icons/facebook.svg
  - assets/icons/apple.svg
  - assets/icons/google.svg
  - assets/images/jukir.png
  - assets/images/facebook.png
  - assets/images/google.png
  - assets/images/profile.png
  - assets/images/user_icon.png
  - assets/images/email_icon.png
  - assets/models/model.tflite
  - assets/models/labels.txt

